# Generated by Django 6.0.4 on 2026-04-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
